---
title: '2018-10-17'
output: html_document
---


```{r}
library(googlesheets)
gs_auth(new_user = TRUE)
gsSurvey<-gs_key("1mC9bnxj11NCNoOCw0Vmn4nxERbHtLjeGo9v9C9b2GDE")  #download sheet information as an object
classSurvey<-gs_read(gsSurvey,ws=1) #access the 1st worksheet
```

```{r}
class(classSurvey)
```

```{r}
(classSurvey$性別 == "男")
(classSurvey$本學期學分數 > 26)
which(classSurvey$性別 == "男" |classSurvey$本學期學分數 > 26)
classSurvey[C(1,4,5,8,10,12,14,15,19,20,23,26,35,37,44,50,51,55,56,57,58)]
```

```{r}
rownames(classSurvey)
(classSurvey$性別 == "男")
(classSurvey$本學期學分數 > 20)
which(classSurvey$性別 == "男" & classSurvey$本學期學分數>26)
classSurvey[c(8,44),3]
```

```{r}
library(readr)
student <- read_csv("https://raw.githubusercontent.com/tpemartin/course-107-1-programming-for-data-science/master/data/student.csv")
library(dplyr)
library(magrittr)
student %<>% mutate(
  身高級距=cut(身高,c(0,150,155,160,165,170,175,180,185,200)))
```

```{r}
which(student$身高 <= 170) -> little
which(student$身高 >= 180) -> tall
which(student$身高 >=170 & student$身高 <= 180) -> m
little
```

```{r}
student$新身高級距 <- student$身高級距
levels(student$新身高級距) <- (0,160]
```


```{r}
dim(classSurvey)
nrow(classSurvey)
ncol(classSurvey)
as.character(classSurvey$學號)
library(stringr)
str_sub(classSurvey$學號,2,4) -> classSurvey$年級
as.factor(classSurvey$年級) -> classSurvey$年級
levels(classSurvey$年級) <- c("大四及以上","大三","大二","大一")
```

```{r}
table(classSurvey$年級)
```

```{r}
as.factor(classSurvey$性別) -> classSurvey$性別
as.factor(classSurvey$年級) -> classSurvey$年級
which(classSurvey$性別 == "男" & classSurvey$年級 != "大一")
```

```{r}
table(classSurvey$性別=="男")
nrow(classSurvey)
```

